[package]
name = "typesig-lisp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
color-eyre = "0.6.3"
smallvec = { version = "1.13.2", features = ["const_generics", "const_new", "union", "write"] }
